### PR TITLE
Update SPANISH

### PR DESCRIPTION
**Pull request by ntrpc-tech**
UPDATE SPANISH LOCALIZATION

### CODE REVIEW

**Comment by ntrpc-tech** [comment]
Sorry for all the changes and everything, new to github, only translating, learning by myself, getting in to it 😄

**Comment by ntrpc-tech** [comment]
Now learned to upload properly ANSI files

**Comment by ntrpc-tech** [comment]
It only remains translation to Save Our Station - Knox Country

**Comment by ntrpc-tech** [comment]
All translation DONE. Sorry for all the text 🥲

**Review by ntrpc-tech — COMMENTED** [review]
And everything checked.

**Comment by YoshiWoof22** [comment]
I've included your translations in PR #8, but because of how I had to apply the changes, I cannot directly merge.

Thank you for your contribution - I'll be adding your name to the workshop credits ASAP!

**Pull request closed without merging**
